### ISSUE TITLE
State not being saved in Azure Storage blob container

### ISSUE THREAD

**Issue by matthewpyost** [XpiritBV/Xpirit-Vsts-Release-Terraform#12]
When using the version 2.* of your VSTS Task from the VSTS marketplace, after running an "apply" command the Terraform state is not being stored in the specified Azure Storages Account. Attached is a screenshot of the configuration. Version 1.* I was able to get the "apply" command to store the state in the storage account. Any help or insights on this issue would be appreciated.
![vsts-task-config](https://user-images.githubusercontent.com/1020789/43228287-a89fc98c-9050-11e8-98f3-ce4e1cf2c103.png)

**Comment by mud5150** [comment]
Hey @matthewpyost I will try to reproduce. Can you post the build logs?

**Comment by mrommelf** [comment]
I am having the same issue with version 2.* has anyone found a solution or work around?

**Comment by mud5150** [comment]
@mrommelf Can you post your build logs? Now that I think about it I wonder if this is an issue with using the new V2 storage account. I gave that a try when it first came out and terraform didn't seem to work with that. You may need to provision an account as v1 blob storage type. Just a guess. If that's not the issue I can take a look at the logs to see if that provides some insight. I have many builds using v2 of the step with state in Azure storage.

**Comment by xtellurian** [comment]
I'm seeing this problem too.
I just created a Storage V1 account, and the state is not persisted there either.

**Comment by xtellurian** [comment]
Perhaps the issue might be with Terraform backend configuration.

I added this file to my terraform project, and the state file was created in Blob storage.

```tf
terraform {
  backend "azurerm" {
    storage_account_name = "tfstatenkadsnf"
    container_name       = "tfstate"
    key                  = "dev.terraform.tfstate"
  }
}
```
Then I override the key when I initialise Terraform in Azure DevOps

![image](https://user-images.githubusercontent.com/8497130/47887264-856e7400-de92-11e8-93a1-b469db4613ce.png)

**Comment by mud5150** [comment]
@xtellurian I will see if I have any problems overriding the key in the arguments field.

**Comment by mud5150** [comment]
@xtellurian Are you specifying a resource group in the backend config? If all of the values in the storage account fields are the same as what's in your backend config you don't need to use the "Specify Storage Account" option.

**Comment by xtellurian** [comment]
This does not work

```tf
terraform {
  backend "azurerm" {
    resource_group       = "tf-master"
    storage_account_name = "tfstatenkadsnf"
    container_name       = "tfstate"
    key                  = "dev.terraform.tfstate"
  }
}
```

![image](https://user-images.githubusercontent.com/8497130/47888353-31668e00-de98-11e8-8f38-5839a114eae6.png)



results in 
![image](https://user-images.githubusercontent.com/8497130/47888338-198f0a00-de98-11e8-9cee-2c01aaa33096.png)

**Comment by mud5150** [comment]
@xtellurian The property name in your backend config should be set to `resource_group_name`

**Comment by xtellurian** [comment]
@mud5150 thanks - that works.
