### ISSUE TITLE
Cannot find path

### ISSUE THREAD

**Issue by jgardner04** [XpiritBV/Xpirit-Vsts-Release-Terraform#14]
I have a build agent on a Windows VM. Running the plan command gives an error that it cannot find path C:\agent\_work\1\s\<myFolder>\<myFileName.tf>. When I go to my actual server that file is in that path. Beyond getting my source, this is my only task.

**Comment by pgroene** [comment]
Can you share the logs from the task? That will probably help.

**Comment by jgardner04** [comment]
@pgroene I emailed you the log files

**Comment by jgardner04** [comment]
Ok, @ivegamsft and I figured out what happened here. The Terraform template path was looking for a folder and not the actual template file. Once I removed the filename the task worked as expected.
