### ISSUE TITLE
Issue with local-exec - az login required

### ISSUE THREAD

**Issue by taras-strypko** [XpiritBV/Xpirit-Vsts-Release-Terraform#18]
Having issue with running az cli script using local-exec provisioner.
Receive next error:
ERROR: Please run 'az login' to setup account
I'm running terraform using VSTS task - https://marketplace.visualstudio.com/items?itemName=petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform
Every other(terraform native) resources are successfully created.

Is there any possibility to run azure cli using local-exec without logging in?
As account is already specified in VSTS task - it seems obvious for me, that command should run in context of that account.

**Comment by ahmedig** [comment]
So I had a look at the extension, and they fortunately save the Azure SPN info into environment variables.
Try this, it works!

```
$subscriptionId = $env:ARM_SUBSCRIPTION_ID
$tenantId = $env:ARM_TENANT_ID
$clientId = $env:ARM_CLIENT_ID
$secret = $env:ARM_CLIENT_SECRET

az.cmd login --service-principal --username $clientId --password $secret --tenant $tenantId --output none
```
