### ISSUE TITLE
Support for DevOps Environment Variables

### ISSUE THREAD

**Issue by eXXL** [XpiritBV/Xpirit-Vsts-Release-Terraform#25]
I combine terraform and some other scripts in one DevOps Release Pipeline.
I need the same variables in Terraform and other scripts that are executed by other tasks.
So I try to use environment variables to set the Terraform input variables.
I set the environment variables in a prior task.

Example:
$ export TF_VAR_image_id=ami-abc123
https://www.terraform.io/docs/configuration/variables.html

Usually this works across tasks within one pipeline:
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables?view=azure-devops&tabs=yaml%2Cbatch#set-in-script

But this variable is not recognized by Terraform when executed with your DevOps task.

**Comment by pgroene** [comment]
Thank you for reporting the issue. I would be happy to accept a pr for this.

**Comment by scott1138** [comment]
@eXXL - What agent are you using and what error are you getting?  Can you post part of your pipeline?

**Comment by eXXL** [comment]
I figured it out by myself. I have to use upper case variable names to make this work because environment variables are upper-cased by the DevOps pipelines.

________________________________
Von: scott1138 <notifications@github.com>
Gesendet: Wednesday, September 25, 2019 6:31:23 AM
An: XpiritBV/Xpirit-Vsts-Release-Terraform <Xpirit-Vsts-Release-Terraform@noreply.github.com>
Cc: eXXL <alexander.ahrens@hotmail.com>; Mention <mention@noreply.github.com>
Betreff: Re: [XpiritBV/Xpirit-Vsts-Release-Terraform] Support for DevOps Environment Variables (#25)


@eXXL<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FeXXL&data=02%7C01%7C%7C1aac2f59b2a14496f46f08d74171391d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637049826846281999&sdata=LCAh69vf2ALR31okOPGwVjzvvI6QJ5Dq6xom0Te8bWY%3D&reserved=0> - What agent are you using and what error are you getting? Can you post part of your pipeline?
