### ISSUE TITLE
Parsing module source link

### ISSUE THREAD

**Issue by JozoSlejko** [XpiritBV/Xpirit-Vsts-Release-Terraform#26]
I'm trying to use module source link to Git repository referencing the module in the ExampleModule subdirectory.

Code example:
`module "example-module" {
source = "git::https://example@dev.azure.com/eg/_git/eg//ExampleModule?ref=master"
}`

The source link gets trunctated to "git::https://example@dev.azure.com/eg/_git/eg?ref=master" basically removing the double slash and the string after it.

Double slash is mandatory in order to specify the subdirectory of the module. 
When using a single slash, the line is not truncated but terraform fails to find the folder.
Is this a parsing bug?

**Comment by pgroene** [comment]
I'm not sure if this is a parsing bug. There are multiple // in the string, if it would be a parsing bug I would expect to fail on the first one. I have limited time to investigate this. You can get the source code to see what causes this. If you find a fix, I'm happy to release a new version with the fix.

**Comment by JozoSlejko** [comment]
Indeed, I just tested, have the exact same issue with another Terraform extension I tried.
Any ideas based on this info maybe?

**Comment by pgroene** [comment]
@JozoSlejko I have no clue, you can download the sources and test it locally. There is some parameter rewriting in the powershell code.

**Comment by JozoSlejko** [comment]
I checked further, the removal of the last // string is something Terraform is always doing when calling git clone.
Git clone operation, when running on the agent, fails even if Agent job has Allow scripts to access OAuth token enabled. It fails with fatal: could not read Password error.
This can be fixed by creating a PAT and adding it to the module URL e.g.

`module "example-module" { source = "git::https://example:PAT@dev.azure.com/eg/_git/eg//ExampleModule?ref=master" }`
