### ISSUE TITLE
Why is "Blob Container Name" required when not using blobstorage shared state?

### ISSUE THREAD

**Issue by tevert** [XpiritBV/Xpirit-Vsts-Release-Terraform#3]
Parameter in question: https://github.com/XpiritBV/Xpirit-Vsts-Release-Terraform/blob/9bfd63c43dfcb9515f8f97fe848b8933844a12b4/Xpirit-Vsts-Release-Terraform/task.json#L101

I'm guessing it's supposed to have `"visibleRule": "ManageState == true"` same as the others.

**Comment by pgroene** [comment]
yes you are correct, I'm fixing the task today
