### ISSUE TITLE
"Manage state in blobstorage" is always true

### ISSUE THREAD

**Issue by tevert** [XpiritBV/Xpirit-Vsts-Release-Terraform#4]
When extracting this parameter in powershell, you need to use the `-AsBool` switch, otherwise it's pulled in as a string and always evaluates to true. This causes complaints about required parameters that aren't even visible.

**Comment by pgroene** [comment]
yes you are correct, I'm fixing it today.

**Comment by pgroene** [comment]
If you do not mind I use the suggestions in the script you uploaded to mp
